- packages/react-jsx-highcharts/src/components/Tooltip/Tooltip.js
- packages/react-jsx-highstock/src/components/RangeSelector/RangeSelector.js
Our application uses universal rendering. It turns out, if there is no `window` in the current environment (such as server rendering), the `'highcharts'` dependency returns a factory function, not the Highcharts namespace instance. Because of this, a failure happens at [Tooltip.js#L16](https://github.com/whawker/react-jsx-highcharts/blob/master/packages/react-jsx-highcharts/src/components/Tooltip/Tooltip.js#L16).
This pull request attempts to solve the problem by checking whether the `Highcharts.defaultOptions` do exist when initializing `Tooltip`'s `defaultProps`, so the application doesn't fail on class definition. Usage of `Highcharts` inside methods (`Highcharts.addEvent()`, `Highcharts.chart()` etc.) needs further research though.
> Do not fail during initalization when Highcharts is not instantiated

- packages/react-jsx-highcharts/.babelrc
- packages/react-jsx-highcharts/build/use-lodash-es.js
- packages/react-jsx-highcharts/package.json
This PR adds ES module build for react-jsx-highcharts.
This lets webpack 4 do tree shaking and module concatenation which saves me around 50kB in final bundle.
As I am not too familiar with the source code, I am not 100% sure that setting "sideEffects": false is entirely safe. On the surface it seems to be.
The sideEffects flag can also be array of globs if there are side effects of importing some modules.
It also modifies the ES build to use lodash-es instead of lodash. That babel plugin is copied from https://github.com/PaulLeCam/react-leaflet
The lodash-es allows some more tree shaking.
As there is no commonjs build, the lodash-es could be used in unmodified source too.
I also tried building UMD with webpack 4 and that also saves some space. I can make separate PR for it if you like?
I …
> Build ES6 module for highcharts

- packages/react-jsx-highcharts/src/components/XAxis/XAxis.js
Removes the xAxis id default value. This makes it possible to add multiple XAxises without providing id's.
Hope it doesn't have any special meaning somewhere else.
> Remove default xaxis id

- packages/react-jsx-highcharts/src/components/Axis/Axis.js
- packages/react-jsx-highcharts/src/components/Series/Series.js
Makes Axis and Series uuid's unique for every instance.
Also drops deprecated componentWillMount from those classes. Options3d I did not know how to test, although removing it from there looks straight forward.
This might not be the cleanest approach, and it might have bugs..
Feel free to ignore if you come up with some better way.
> Fix uuid uniqueness

- packages/react-jsx-highcharts/package.json
- packages/react-jsx-highstock/package.json
Running npm audit had warnings about mocha and lodash:
https://nodesecurity.io/advisories/534 
https://nodesecurity.io/advisories/146 
https://nodesecurity.io/advisories/577 
I don't know if these are at all relevant with this library, but it shows good style to upgrade them:)
> Upgrade mocha & lodash

- packages/react-jsx-highstock-datepickers/.babelrc
- packages/react-jsx-highstock-datepickers/package.json
- packages/react-jsx-highstock-datepickers/webpack.config.js
This updates datepickers to use webpack 4. Doesn't save much space, but it is more consistent with other modules.
I didn't test this at all, because I have never used it. Hope it still helps a little to release 3.0.0.
> Update datepickers build to webpack 4

- packages/react-jsx-highcharts/src/components/DelayRender/DelayRender.js
Managed to run into this.
If axis is unmounted too quickly, React gives a warning:
"Can't call setState (or forceUpdate) on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method."
In reality the warning tells that there is something wrong in my own code, but here's a fix anyway.
> Fix cannot set state on unmounted component

- packages/react-jsx-highcharts/src/components/Axis/Axis.js
- packages/react-jsx-highcharts/src/components/Series/Series.js
- packages/react-jsx-highcharts/src/utils/events.js
- packages/react-jsx-highcharts/test/components/Axis/Axis.spec.js
- packages/react-jsx-highcharts/test/components/Series/Series.spec.js
- packages/react-jsx-highcharts/test/utils/events.spec.js
This saves a couple of unnecessary redraw calls when adding axis or series. I found the calls while doing profiling.
It does it by chart.addAxis and chart.addSeries calls to have redraw = false. Then it relies on the last call to addEventProps to call updateFn with redraw = true.
Also this treats render() as lifecycle method so that Axis and Series don't need to call this.forceUpdate.
> Redraw only once on mount, remove forced updates

- packages/react-jsx-highcharts/src/components/Axis/Axis.js
- packages/react-jsx-highcharts/src/components/Series/Series.js
- packages/react-jsx-highcharts/test/components/Axis/Axis.spec.js
- packages/react-jsx-highcharts/test/components/Series/Series.spec.js
- packages/react-jsx-highcharts/test/components/Series/SeriesTypes.spec.js
It's pretty straight forward, but I don't know the history of adding the event handlers with update, so decided to ask for review.
And this is not urgent by any means.
edit: it also seems to fix sankey series problem, removed the hack for it
> Add eventhandlers to Axis and Series when they are created

- packages/react-jsx-highcharts/src/index.js
Creates the ability to provide a custom withHighcharts HOC. I need this because I am using react-docgen to generate documentation for the Highcharts components. react-docgen creates an error with the existing HOC: Error: No suitable component definition found.
It would be awesome if you could merge this simple addition to the export list. Would help me not to have to fork / republish.
> Export Consumer and Provider context in index.js

- packages/react-jsx-highcharts/package.json
Babel runtime is missing from dependencies. I guess it was removed accidentally by https://github.com/whawker/react-jsx-highcharts/commit/fcb445ff0577341c2d76206682c054d642f5a6bd
This PR adds it back.
Probably needs a release, otherwise some people might have problems using the library.
> Add back missing @babel/runtime

- .eslintrc
- packages/react-jsx-highcharts/package-lock.json
- packages/react-jsx-highcharts/package.json
- packages/react-jsx-highcharts/src/components/AxisProvider/index.js
- packages/react-jsx-highcharts/src/components/BaseChart/BaseChart.js
- packages/react-jsx-highcharts/src/components/ChartProvider/index.js
- packages/react-jsx-highcharts/src/components/Highcharts3dChart/Highcharts3dChart.js
- packages/react-jsx-highcharts/src/components/HighchartsProvider/index.js
- packages/react-jsx-highcharts/src/components/HighchartsSparkline/HighchartsSparkline.js
- packages/react-jsx-highcharts/src/components/SeriesProvider/index.js
- packages/react-jsx-highmaps/package-lock.json
- packages/react-jsx-highmaps/package.json
- packages/react-jsx-highmaps/src/components/HighchartsMapChart/HighchartsMapChart.js
- packages/react-jsx-highstock-datepickers/package.json
- packages/react-jsx-highstock-datepickers/src/index.js
- packages/react-jsx-highstock/package-lock.json
- packages/react-jsx-highstock/package.json
I added eslint-plugin-react-perf to detect performance problems in eslint.
It currently errors out, but it could prevent problems like #216.
@whawker do you think these rules should be turned into warnings and merge this to master? After fixing these the rules should probably be turned to errors.
> Add eslint-plugin-react-perf and fix errors

- packages/react-jsx-highcharts/src/index.js
Contexts are better accessed through hooks like useHighcharts.
This makes it easier for us to make changes to context behavior.
> Don't export contexts

- packages/react-jsx-highcharts/src/components/Chart/Chart.js
- packages/react-jsx-highcharts/src/components/UseManualEventHandlers/index.js
- packages/react-jsx-highcharts/src/utils/events.js
- packages/react-jsx-highcharts/test/components/Chart/Chart.spec.js
- packages/react-jsx-highcharts/test/test-utils.js
- packages/react-jsx-highcharts/test/utils/events.spec.js
This allows chart event handlers to be updated.
When parent component is hooks based, the passed in event handler might need to change:
```javascript
const onSelection = useCallback(() => {
// do something with prop that changes
}, [props.somechangingprop]);
```
> Allow Chart event handlers to be updated

- packages/react-jsx-highcharts/src/components/WithHighcharts/index.js
- packages/react-jsx-highcharts/src/index.js
- packages/react-jsx-highmaps/src/index.js
Adds WithHighcharts component that could replace last HOC withHighcharts.
usage:
```jsx
import Highcharts from 'Highcharts';
<WithHighcharts Highcharts={Highcharts}>
<HighchartsChart .... />
</WithHighcharts>
```
> Add WithHighcharts component

- packages/react-jsx-highcharts/src/components/ColorAxis/ColorAxis.js
As found in #251, creating highcharts objects outside of useEffect is not safe in all cases.
Quite straightforward, I think it can be merged immediately.
> Create coloraxis inside useEffect

- packages/react-jsx-highcharts/src/components/Series/Series.js
- packages/react-jsx-highcharts/test/components/Series/Series.spec.js
I felt uneasy about changing the behaviour of Lodash's `isEqual` to `Object.is`, I fear it may create confusion when upgrading versions.
Therefore, I have added an `isDataEqual` prop to `Series`, of the form
```js
(data, prevData) => boolean
``` 
If the returned boolean is 
* `true` - data hasn't changed, then `setData` *isn't* called
* `false`- data *has* changed, so `setData` is called
This allows users to override the default `Object.is` behaviour, and re-inject Lodash's `isEqual` if they choose.
> Add a isDataEqual prop, for custom Series data comparison

- packages/react-jsx-highcharts/src/components/Series/Series.js
- packages/react-jsx-highcharts/test/components/ColorAxis/ColorAxis.integration.spec.js
After 462bfd606d8b799b725effe429bf75cf3973e5e0 it is not possible to reference coloraxis by id in Series.
I think we should just remove support for it now, and require coloraxis to be referenced from context.
The coloraxis can anyway be referenced from Series with:
```jsx
<Series colorAxis="myColorAxis" />
```
So it's not a big deal.
> Don't allow coloraxis to be referenced by id

- packages/react-jsx-highcharts/package.json
- packages/react-jsx-highmaps/package.json
- packages/react-jsx-highstock/package.json
Highcharts 8 doesn't seem to have any breaking changes, so this isn't technically needed now.
On the other hand Highcharts 7 doesn't get updates anymore, so it would be easier to drop support now if anything in Highchart 8 helps us to make simpler code.
What do you think?
> Drop support for highchart < 8

- packages/react-jsx-highcharts/src/utils/debounce-raf.js
This should fix the issue reported in https://github.com/whawker/react-jsx-highcharts-examples/issues/2
Importing debounce-raf caused exception when window was not available.
> Fix importing in SSR app

- packages/react-jsx-highcharts/babel.config.js
- packages/react-jsx-highmaps/babel.config.js
- packages/react-jsx-highstock/babel.config.js
This sets used runtime version for @babel/transform-runtime.
https://babeljs.io/docs/en/babel-plugin-transform-runtime#version
It results in a much smaller bundle, as transform can depend on newer features be present on runtime.
react-jsx-highcharts bundle: 36586 - 29043 = 7543 bytes saved.
> Set babel runtime version to make smaller bundle

- .prettierrc
- packages/react-jsx-highcharts/package-lock.json
- packages/react-jsx-highcharts/package.json
- packages/react-jsx-highcharts/src/components/UseManualEventHandlers/index.js
- packages/react-jsx-highcharts/src/utils/debounce-raf.js
- packages/react-jsx-highcharts/src/utils/pickBy.js
- packages/react-jsx-highcharts/test/components/Series/Series.spec.js
- packages/react-jsx-highmaps/package-lock.json
- packages/react-jsx-highmaps/package.json
- packages/react-jsx-highmaps/src/components/MapNavigation/MapNavigationZoomIn.js
- packages/react-jsx-highmaps/src/components/MapNavigation/MapNavigationZoomOut.js
- packages/react-jsx-highstock/package-lock.json
- packages/react-jsx-highstock/package.json
Upgrade to prettier v2. 
Prettier v2 changed some formatting defaults which I mostly configured back.
Another change is [default endOfLine](https://prettier.io/docs/en/options.html#end-of-line). It can be fixed with either configuring it to auto, or:
> Add * text=auto eol=lf to the repo's .gitattributes file. You may need to ask Windows users to re-clone your repo after this change to ensure git has not converted LF to CRLF on checkout.
Either one is still needed for this PR, which one you prefer?
> Upgrade to prettier v2

- packages/react-jsx-highcharts/src/components/BaseChart/BaseChart.js
As discussed [here](https://github.com/whawker/react-jsx-highcharts/issues/282) I add containerProps to BaseChart in order to add style to HighchartsReact and make it responsive relative to parent container.
I tested it and seems is working (with the example reporeted on issue linked before).
Let me know if I need to add more.
> Add containerProps to BaseChart

- packages/react-jsx-highcharts/src/components/Tooltip/Tooltip.js
- packages/react-jsx-highcharts/test/components/Tooltip/Tooltip.spec.js
This fixes #289.
Now the Tooltip does not get recreated on mount, which might lead to settings leaking from previous tooltip options. But now both pointFormat and enabled props work at the same time.
It might be possible to store chart.options.tooltip.userOptions on mount and restore it on unmount, but that might cause more trouble.
@whawker what do you think?
> Fix tooltip not updating properly

- packages/react-jsx-highcharts/src/components/Series/Series.js
- packages/react-jsx-highcharts/test/components/Series/Series.spec.js
To allow overriding the default value (true) when calling setData.
In our project, with animations turned off, we don't need to update points for any visual effect and we noticed a huge performance improvement on large data sets with `updatePoints` set to false.
Please let me know if there are other changes throughout the codebase necessary as well and feel free to push updates on this branch.
> Expose 'updatePoints' parameter of setData

- packages/react-jsx-highmaps/src/components/HighchartsMapChart/HighchartsMapChart.js
- packages/react-jsx-highmaps/test/components/HighchartsMapChart/HighchartsMapChart.spec.js
It looks like the chart that was being returned in the callback prop is the chart that is passed as a prop (thus `undefined` if no chart is passed). This pull request changes the instance returned in the callback and adds a test to ensure that the chart return is defined.
> Return the map chart instance to the callback prop

- packages/react-jsx-highcharts/src/components/Chart/Chart.js
- packages/react-jsx-highcharts/test/components/Chart/Chart.spec.js
This is a workaround for #299.
Also this now allows height and width to be set 0 or null.
> Do not call chart.setSize when both height and width are undefined

- packages/react-jsx-highcharts/README.md
- packages/react-jsx-highmaps/README.md
- packages/react-jsx-highstock-datepickers/README.md
- packages/react-jsx-highstock/README.md
This removes mentions of withHighcharts in the READMEs. Also adds "DEPRECATED" to react-jsx-highstock-datepickers.
I think the react-jsx-highstock-datepickers should also be deprecated in npm registry with:
```sh
npm deprecate react-jsx-highstock-datepickers "<message>"
```
https://docs.npmjs.com/deprecating-and-undeprecating-packages-or-package-versions
> Update README to point to HighchartsProvider instead of withHighcharts

- packages/react-jsx-highstock/README.md
Fix rangeselector example in react-jsx-highstock readme.
Closes #305
> Move rangeselector after xaxis in readme

- packages/react-jsx-highcharts/src/components/Axis/Axis.js
- packages/react-jsx-highcharts/src/components/BaseChart/BaseChart.js
- packages/react-jsx-highcharts/src/components/ColorAxis/ColorAxis.js
- packages/react-jsx-highcharts/src/components/Series/Series.js
[In React 17 the effect cleanup functions run asynchronously.](https://reactjs.org/blog/2020/08/10/react-v17-rc.html#effect-cleanup-timing).
This PR changes the cleanup functions so, that they should work in React 17 too.
React 17 should release this week.
> Fix effect cleanups for react 17

- packages/react-jsx-highcharts/package-lock.json
- packages/react-jsx-highcharts/package.json
- packages/react-jsx-highcharts/src/components/Series/Series.js
- packages/react-jsx-highcharts/test/ContextSpy.js
- packages/react-jsx-highcharts/test/components/Series/Series.integration.spec.js
- packages/react-jsx-highcharts/test/components/Series/Series.spec.js
- packages/react-jsx-highcharts/test/components/Series/SeriesTypes.integration.spec.js
This adds code to change series eventhandlers when they are changed in the props.
Somewhat related to #308.  If there are no problems with updating series eventhandlers, then it should not be too hard to use same mechanism in axis too.
I had to add dependency for react-testing-library as the tests were incredibly complex with enzyme. I am hoping we could migrate the other tests use react-testing-library as well.
> Allow series eventhandlers to be updated

- packages/react-jsx-highcharts/package.json
- packages/react-jsx-highstock/package.json
It's needed when building on Windows.
Also removing full path to webpack binary as npm figures that out on
itself.
> Use cross-env in build:es script

- packages/react-jsx-highstock/package-lock.json
- packages/react-jsx-highstock/package.json
- packages/react-jsx-highstock/tsconfig.json
- packages/react-jsx-highstock/types/index.d.ts
This builds on #303 and extends types to also cover the
react-jsx-highstock package.
Please verify that the type definitions makes sense, @anajavi and and
@whawker. I used the types you defined, @anajavi, as reference and tried
to compare props of RJH components with Highcharts config types.
It works for our usage of RJH, but not all components are tested.
> Add typescript definitions for react-jsx-highstock

- package-lock.json
- packages/react-jsx-highmaps/jest.config.js
- packages/react-jsx-highmaps/package.json
- packages/react-jsx-highmaps/src/components/MapNavigation/MapNavigationButton.js
- packages/react-jsx-highmaps/webpack.config.js
Remove last use of lodash in react-jsx-highmaps.
It was surprisingly simple fix.
> Drop lodash dependency from react-jsx-highmaps

- package-lock.json
- package.json
- packages/react-jsx-highcharts/package.json
- packages/react-jsx-highmaps/package.json
- packages/react-jsx-highstock/package.json
This allows highcharts v10 in peer dependencies.
Tests pass and it seems to work okay.
> Support highcharts v10

- packages/react-jsx-highcharts/test/components/YAxis/YAxis.spec.js
- packages/react-jsx-highcharts/test/components/ZAxis/ZAxis.spec.js
continuation of #385
in order to support react 19
> Replace Y&Z axis shallow tests

- packages/react-jsx-highmaps/test/ContextSpy.js
- packages/react-jsx-highmaps/test/components/XAxis/XAxis.spec.js
- packages/react-jsx-highmaps/test/components/YAxis/YAxis.spec.js
continuation of #385
in order to support react 19
```<ContextSpy>``` is copied from highcharts tests
This should be last shallow-renderer replacement.
> Replace highmaps shallow tests
